// Autogenerated by geninfo.sh, do not edit

package sgextensions;

public class Info
{
	static final String modName = "SG Craft - Darkcraft Edition";
	static final String modID = "SGCraft";
	static final String modPackage = "sg";
	static final String versionNumber = "0.4.1";
	static final String versionBounds = "[0.4.1,0.4.1)";
}
